### ISSUE TITLE
cannot select a dot if there are 2+ overlapping dots

### ISSUE THREAD

**Issue by scampi** [Felixls/kibi_scatterplot_vis#1]
![2016-09-13-142605_1505x741_scrot](https://cloud.githubusercontent.com/assets/795879/18475411/366d600e-79be-11e6-8056-58f00e7e736f.png)

**Comment by Felixls** [comment]
Ok, Then I will remove the dot selection, it just impossible to accomplish (i.e if thousand of point are in the same place).

Thks.
