### ISSUE TITLE
Colors too similar?

### ISSUE THREAD

**Issue by jccq** [Felixls/kibi_scatterplot_vis#11]
Are we using the kibana functions to select colors in histograms/piechart? i believe by default they provide more contrasted colors.. i am colorblind this choice for 2 is pretty bad for me.. i can see some difference but not enough - could it be the default kibana function can do better?

![image](https://cloud.githubusercontent.com/assets/4949704/19059689/c0538aa2-89d9-11e6-8e07-7cda55cee2bd.png)

**Comment by Felixls** [comment]
I have changed category20 (d3) to category10. In the future this will need a refactor.

**Comment by jccq** [comment]
please do give it a check if the colors are really working today in my tests they were kind of.. dont know i am partially colorblind so might be the wrong person please do give it a try
