### ISSUE TITLE
option to "shift" values a bit (multiple series)

### ISSUE THREAD

**Issue by jccq** [Felixls/kibi_scatterplot_vis#14]
One should have the option to have multiple timeseries shifted lightely with respect to the main X asis (at least X).

E.g. type A B C D may be distinguished by color.. ok .. but if on has 10 values on X axis (that is, a relatively small number) then colors will overlap and this will be confusing.

Just an idea: get the minimum size of the dot (2?) and check how many such diameters can fit confortably into 1/6th of the space between one X and the others. That defines the number of buckets we can has a value from to define . 

Buckets can be before or after the actual X marker

![image](https://cloud.githubusercontent.com/assets/4949704/19078416/f04cc732-8a47-11e6-9daf-4638ecbb0e4d.png)

**Comment by Felixls** [comment]
Added @ master
