### ISSUE TITLE
separate the veriables by type in dropdowns

### ISSUE THREAD

**Issue by jccq** [Felixls/kibi_scatterplot_vis#16]
useful to see what is numeric and what is not as in other kibana components (maybe possible to reuse a same reusable component? would be good because we'll extend that evenctually)

![image](https://cloud.githubusercontent.com/assets/4949704/19108337/6030aaa0-8ae8-11e6-9a52-187ffff9f32f.png)

**Comment by Felixls** [comment]
Fixed @ master version
