### ISSUE TITLE
Jitter on non numeric codes

### ISSUE THREAD

**Issue by jccq** [Felixls/kibi_scatterplot_vis#19]
When a non numeric code is selected, the jutter brings everything to the extreme left. In this case the only category was "glucose" (jitter label = color label) so .. strangely all is flattened to the left.

![image](https://cloud.githubusercontent.com/assets/4949704/19109336/c1e5a468-8aec-11e6-9144-85930df386ad.png)

my expectation would be that : 

1) the number of different categories of the nonnumeric code is calculated (e.g. in the sample there are 5 categories) 
2) the dots are placed in 5 thin columns (not spread across the bucket) which are one next to the other 

the result will be like in the PIC

e.g. here the RED BLUE and BLACK represent different JITTER NON NUMERICAL VALUES 

e.g. RED = "red blood cell" kind of result Black = "Albumin" etc.

this way for each bucket (e.g. Visit 1) i can see red blod cell and albumin next to each other

![image](https://cloud.githubusercontent.com/assets/4949704/19078416/f04cc732-8a47-11e6-9daf-4638ecbb0e4d.png)

**Comment by Felixls** [comment]
Fixed @ master version
