### ISSUE TITLE
Incoherent results in numeric Jitter

### ISSUE THREAD

**Issue by jccq** [Felixls/kibi_scatterplot_vis#21]
I am getting very incoherent results with the numeric jitter.

i believe you're using the very first few (5/10? samples) to then decide for the rest.. but this causes causes problems.. just rotate among the different scaling options and you will see that some are acceptable (produce results where one can still understand the category e.g. there is at least half bucket size which always remains white

other times it doesnt work.

This is good (using age to jitter)

![image](https://cloud.githubusercontent.com/assets/4949704/19110131/5e9a17a0-8af0-11e6-8355-4642e5f373f6.png)

however if i refresh i can get it wrong

![image](https://cloud.githubusercontent.com/assets/4949704/19110153/7d971130-8af0-11e6-837c-65bd8544e40b.png)

and wrong again

![image](https://cloud.githubusercontent.com/assets/4949704/19110193/9e37b638-8af0-11e6-8946-de0cf6827ec4.png)

and wrong again
and wrong again
and right (about 1/5 ?)

![image](https://cloud.githubusercontent.com/assets/4949704/19110238/c4eaeca0-8af0-11e6-8cfb-5416ea1f34c2.png)

similarly LOG

this is correct (i think) though not properly spaced anyway

![image](https://cloud.githubusercontent.com/assets/4949704/19110285/0274c118-8af1-11e6-8a5b-2b72fb7ade79.png)

this is refreshing

![image](https://cloud.githubusercontent.com/assets/4949704/19110303/1467726c-8af1-11e6-926d-12d154a15e9e.png)

**Comment by Felixls** [comment]
Please, check this with the last version @ master
