### ISSUE TITLE
Log scaling seems wrong

### ISSUE THREAD

**Issue by jccq** [Felixls/kibi_scatterplot_vis#23]
![image](https://cloud.githubusercontent.com/assets/4949704/19214628/4af8e19e-8d80-11e6-8a3b-5afc17dc071e.png)

![image](https://cloud.githubusercontent.com/assets/4949704/19214648/912189c8-8d80-11e6-9763-cc001c7b299f.png)

**Comment by Felixls** [comment]
Fixed on master version
