### ISSUE TITLE
scatterplot does not react to relational panel

### ISSUE THREAD

**Issue by jccq** [Felixls/kibi_scatterplot_vis#27]
It works with relational filters (clicking a button from companies to articles) but it doesnt seem to listed to the "relational filter" 

![image](https://cloud.githubusercontent.com/assets/4949704/19219631/4d26bcee-8e10-11e6-9171-ace951cb11d2.png)
![image](https://cloud.githubusercontent.com/assets/4949704/19219636/68ad6f44-8e10-11e6-9760-48a0b8bff950.png)

In the screenshot above i have a filter on companies (e.g. european companies) and then i have activated the relational filter . As you can see the signiticant terms table is updated but not the scatterplot showing as if there was no filter.

**Comment by Felixls** [comment]
Fixed in the last release
