### ISSUE TITLE
some configuration input are disabled after staging the changes

### ISSUE THREAD

**Issue by scampi** [Felixls/kibi_scatterplot_vis#3]
I've seen this problem with the `Color` and `Dot size` menus:

![2016-09-13-143604_347x366_scrot](https://cloud.githubusercontent.com/assets/795879/18475709/65e26252-79bf-11e6-878d-4e85efe30025.png)

**Comment by Felixls** [comment]
Hi scampi, Color and Color field are mutual exclusive settings.

I.e: You can select **Color field** = "number_of_employees" and the colors will be set by category20 scale, whereas that **Color** will set the color of the circles with d3.rgb

**Comment by scampi** [comment]
ah ok makes sense
