### ISSUE TITLE
Better scaling for dot size

### ISSUE THREAD

**Issue by jccq** [Felixls/kibi_scatterplot_vis#7]
Here i am trying to plot the age as dot size..

![image](https://cloud.githubusercontent.com/assets/4949704/19059569/b5dc8f5c-89d8-11e6-8eed-9641ef0702d2.png)

:) Kibana "Line" plot has an option with a slider that makes the dot size more or less sensible to the underlying value, i am not sure what formula it uses. but maybe worth looking at it? alternatively a multiplier + choice between linear, log2, Sqrt() ?

**Comment by Felixls** [comment]
I have added dot size scale
