### ISSUE TITLE
Y axes label precision

### ISSUE THREAD

**Issue by jccq** [Felixls/kibi_scatterplot_vis#8]
Kibana has defailts for numeric label precisions (they are set in the properties of the field), the component should use the defaults for that fields and apply them for formatting the numbers..

![image](https://cloud.githubusercontent.com/assets/4949704/19059629/342a9a84-89d9-11e6-867e-87a8f786f46e.png)

**Comment by jccq** [comment]
in some cases the numbers are long, in others they are short..

![image](https://cloud.githubusercontent.com/assets/4949704/19059732/0c2826d6-89da-11e6-886a-b17dd326d869.png)

**Comment by Felixls** [comment]
Same problem as #13
