### ISSUE TITLE
Overlapping labels

### ISSUE THREAD

**Issue by jccq** [Felixls/kibi_scatterplot_vis#9]
I knwo this has been a hard issue for some other visualization in kibana

how to prevent labels from excessively overlapping?

![image](https://cloud.githubusercontent.com/assets/4949704/19059636/47b97e26-89d9-11e6-8549-7760725483ec.png)

**Comment by Felixls** [comment]
Perhaps the Y field type is not a number? What is the definition of the field?

**Comment by Felixls** [comment]
Same problem as #13

**Comment by jccq** [comment]
I was kind of saying we should void overlapping labels eg skipping labels
when they are too many can we try?
